# Generated by Django 5.0.2 on 2024-03-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colleges',
            fields=[
                ('collid', models.IntegerField(primary_key=True, serialize=False)),
                ('collfullname', models.CharField(max_length=100)),
                ('collshortname', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'colleges',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('deptid', models.IntegerField(primary_key=True, serialize=False)),
                ('deptfullname', models.CharField(max_length=100)),
                ('deptshortname', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'departments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('progid', models.IntegerField(primary_key=True, serialize=False)),
                ('progfullname', models.CharField(max_length=100)),
                ('progshortname', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'programs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('studid', models.IntegerField(primary_key=True, serialize=False)),
                ('studfirstname', models.CharField(max_length=50)),
                ('studlastname', models.CharField(max_length=50)),
                ('studmidname', models.CharField(blank=True, max_length=50, null=True)),
                ('studprogid', models.IntegerField()),
                ('studyear', models.IntegerField()),
            ],
            options={
                'db_table': 'students',
                'managed': False,
            },
        ),
    ]
